import { useEffect, useState } from 'react';
import toast from 'react-hot-toast';
import { categoryAPI } from '../../api';

const flatten = (items, depth = 0) => items.flatMap((item) => [{ ...item, depth }, ...flatten(item.children ?? [], depth + 1)]);

export default function CategoryManagementPage() {
  const [tree, setTree] = useState([]); const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [parentId, setParentId] = useState('');
  const load = () => categoryAPI.list().then(({ data }) => setTree(data ?? [])).catch(() => toast.error('Unable to load categories.'));
  useEffect(() => { load(); }, []);
  const entries = flatten(tree);
  const create = async (event) => { event.preventDefault(); if (!name.trim()) return; try { await categoryAPI.create({ name: name.trim(), description }, parentId || undefined); setName(''); setDescription(''); setParentId(''); load(); toast.success('Category saved.'); } catch (error) { toast.error(error.response?.data?.message || 'Unable to save category.'); } };
  const remove = async (category) => { if (!window.confirm(`Delete ${category.name} and its child categories?`)) return; try { await categoryAPI.delete(category.id); load(); toast.success('Category deleted.'); } catch { toast.error('Unable to delete category.'); } };
  return <div className="container fade-in"><div className="page-header"><h1 className="page-title">Question categories</h1><p className="page-subtitle">Organize the shared question bank with parent and child categories.</p></div><div style={{ display: 'grid', gridTemplateColumns: 'minmax(0, 1fr) 360px', gap: 24 }}><div className="card"><div className="card-title" style={{ marginBottom: 14 }}>Category hierarchy</div>{entries.length === 0 ? <div className="empty-state"><div className="empty-subtitle">Create the first category to organize questions.</div></div> : <div className="question-stack">{entries.map((category) => <div className="choice-option" key={category.id} style={{ justifyContent: 'space-between', paddingLeft: 16 + category.depth * 28 }}><div><strong>{category.depth > 0 ? '↳ ' : ''}{category.name}</strong>{category.description && <div className="text-secondary" style={{ fontSize: 13, marginTop: 3 }}>{category.description}</div>}</div><button className="btn btn-ghost btn-sm" onClick={() => remove(category)}>Delete</button></div>)}</div>}</div><form className="card" onSubmit={create}><div className="card-title">Add category</div><label className="label" style={{ display: 'block', marginTop: 14 }}>Name<input className="input" required value={name} onChange={(event) => setName(event.target.value)} /></label><label className="label" style={{ display: 'block', marginTop: 12 }}>Parent category (optional)<select className="select" value={parentId} onChange={(event) => setParentId(event.target.value)}><option value="">Top-level category</option>{entries.map((category) => <option key={category.id} value={category.id}>{'— '.repeat(category.depth)}{category.name}</option>)}</select></label><label className="label" style={{ display: 'block', marginTop: 12 }}>Description<textarea className="textarea" value={description} onChange={(event) => setDescription(event.target.value)} /></label><button className="btn btn-primary" style={{ marginTop: 16 }}>Save category</button></form></div></div>;
}
